"""
_____________________________________________________________________________
 Haciendo uso de la página de Kaggle, seleccionar tres diferentes datasets.
    C) Un gráfico circular
Enlace al dataset utilizado: 
______________________________________________________________________________
"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar el dataset de China vs Japon
paises = pd.read_csv('dataset/Big_Japan_vs_China_Technology.csv')
